backend-developers-ltd/ComputeHorde

- executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
- executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py
- GC volumes
- GC docker images
- Ignore common base images in GC
Added the test removed in the previous PR (it was blocking on GC).
> Clean after executor run

- .github/workflows/validator_ci.yml
Validator doesn't have any test right now, but it is good to have linting/formatting checks in CI.
> Add validator lint/test to CI

- validator/app/src/compute_horde_validator/validator/facilitator_client.py
> spec sending refactor logs

- compute_horde/compute_horde/test_base/__init__.py
- compute_horde/pyproject.toml
- executor/bin/rotate-local-backups.py
- executor/pyproject.toml
- miner/bin/rotate-local-backups.py
- miner/pyproject.toml
- validator/app/src/compute_horde_validator/validator/organic_jobs/facilitator_client.py
- validator/app/src/compute_horde_validator/validator/tests/helpers.py
- validator/app/src/compute_horde_validator/validator/tests/test_commands.py
- validator/app/src/compute_horde_validator/validator/tests/test_facilitator_client.py
- validator/app/src/compute_horde_validator/validator/tests/test_utils.py
- validator/bin/rotate-local-backups.py
- validator/pyproject.toml
https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
> Add bugbear ruleset to ruff config

- validator/app/src/compute_horde_validator/settings.py
- validator/app/src/compute_horde_validator/validator/cross_validation/prompt_answering.py
- validator/app/src/compute_horde_validator/validator/cross_validation/prompt_generation.py
- validator/app/src/compute_horde_validator/validator/cross_validation/utils.py
- validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
- validator/app/src/compute_horde_validator/validator/tasks.py
- validator/app/src/compute_horde_validator/validator/tests/conftest.py
- validator/app/src/compute_horde_validator/validator/tests/settings.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_system_events.py
- validator/app/src/compute_horde_validator/validator/tests/test_system_events.py
I am a bit concerned about querying the `SystemEvent` model. It can be a really big table if validators don't prune it regularly.
> Improve LLM system events

- validator/app/src/compute_horde_validator/validator/tasks.py
`not success_count` will always be 0 if there was at least 1 success :]
> Fix failure_count

- install_miner.sh
- validator/README.md
better README explanation of VALIDATOR_PUBLIC_KEY param of install_miner
> Better README explanation of VALIDATOR_PUBLIC_KEY param of install_miner

- README.md
> Troubleshooting: how to get vali logs

- README.md
> cosmetic README fixes

- compute_horde/compute_horde/miner_client/organic.py
- compute_horde/tests/conftest.py
- compute_horde/tests/test_receipts_transfer.py
- compute_horde/tests/test_validators.py
- validator/app/src/compute_horde_validator/validator/tests/test_cross_validation/conftest.py
- validator/app/src/compute_horde_validator/validator/tests/test_cross_validation/test_prompt_answering.py
- validator/app/src/compute_horde_validator/validator/tests/test_cross_validation/test_prompt_generation.py
- validator/app/src/compute_horde_validator/validator/tests/test_facilitator_client.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/conftest.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_batch.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_llm_synthetic_job_flow.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_multiple_miners.py
- validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_single_miner.py
- validator/app/src/compute_horde_validator/validator/tests/transport.py
Some small touch-ups that are on my bigger job routing branch but are unrelated to the routing. Should decrease the noise in the big PR that is to come.
> miscellaneous touch-ups

- miner/app/src/compute_horde_miner/miner/management/commands/debug_create_random_receipts.py
- validator/app/src/compute_horde_validator/validator/management/commands/transfer_receipts.py
(and because it's probably a good idea)
> reuse subtensor instance to avoid a memory leak 

- facilitator/app/envs/prod/Dockerfile
- facilitator/devops/scripts/build-backend.sh
Fixes docker builds: https://github.com/backend-developers-ltd/ComputeHorde/actions/runs/13577354855/job/37956504793
> fix facilitator cd

- pyproject.toml
Will be useful for IDE integration, should not break anything as CI and scripts are ran in subdirectories
> Add Ruff config to root pyproject.toml

- README.md
> Docs: peak formula explained

- compute_horde/compute_horde/utils.py
- validator/app/src/compute_horde_validator/validator/tests/conftest.py
- validator/app/src/compute_horde_validator/validator/tests/helpers.py
Is this still correct: `MIN_STAKE = 1000`? @mateuszsrebrny-reef
> Check validator stake based on total effective stake

- compute_horde_sdk/README.md
- compute_horde_sdk/docs/source/api/client.rst
- compute_horde_sdk/docs/source/api/exceptions.rst
- compute_horde_sdk/docs/source/api/jobs.rst
- compute_horde_sdk/docs/source/conf.py
- compute_horde_sdk/docs/source/index.rst
- compute_horde_sdk/docs/source/quickstart.rst
- compute_horde_sdk/src/compute_horde_sdk/_internal/exceptions.py
- compute_horde_sdk/src/compute_horde_sdk/_internal/models.py
- compute_horde_sdk/src/compute_horde_sdk/_internal/sdk.py
- compute_horde_sdk/tests/unit/api/test_sdk.py
* Update README
* Fix typo "unsuccessfully" in `is_successful()`
* Change spelling everywhere to "ComputeHorde" for consistency
* Change the way `ComputeHordeJobSpec` is documented – now it shows types in the rendered docs
* Add missing `ExecutorClass` to the documentation
To see changes, you can do 
```
uv run sphinx-build -b html docs/source/ docs/build/html
```
> Improve SDK docs

- compute_horde_sdk/docs/source/index.rst
> [sdk] slightly better sphinx intro

- .github/workflows/compute_horde_sdk_cd_docs.yml
- .gitignore
- compute_horde/uv.lock
- compute_horde_sdk/devops/tf/docs/.envrc.example
- compute_horde_sdk/devops/tf/docs/backend.tf
- compute_horde_sdk/devops/tf/docs/main.tf
- compute_horde_sdk/devops/tf/docs/terraform.tfvars
- compute_horde_sdk/devops/tf/docs/vars.tf
- compute_horde_sdk/docs/source/_templates/gh-pages-redirect.html
- compute_horde_sdk/docs/source/_templates/versions.html
- compute_horde_sdk/docs/source/conf.py
- compute_horde_sdk/noxfile.py
- compute_horde_sdk/pyproject.toml
- compute_horde_sdk/uv.lock
- executor/uv.lock
- facilitator/uv.lock
- miner/uv.lock
- validator/uv.lock
Available here:
https://sdk.computehorde.io/
> Publish SDK docs

- docs/preload-job-images.sh
- miner/README.md
Tested the script locally and on our 2 executors (installed as a cron job).
> Add script and docs to preload job images

- README.md
- miner/README.md
- validator/README.md
> Docs: collateral and ddos links

- validator/app/src/compute_horde_validator/validator/job_excuses.py
Add logs for receipt validation failures in validator.
> Log receipt validation failures in validator

- .github/workflows/executor_cd_testing.yml
- .github/workflows/facilitator_cd.yml
- .github/workflows/facilitator_cd_testing.yml
- .github/workflows/miner_cd_testing.yml
- .github/workflows/miner_runner_cd_testing.yml
- .github/workflows/validator_cd_testing.yml
- .github/workflows/validator_runner_cd_testing.yml
- facilitator/deploy.sh
- facilitator/envs/dev/docker-compose.yml
- facilitator/envs/prod/docker-compose.yml
Added CD for the "testing" environment.
Mostly copied over staging actions and replaced with "testing".
Facilitator CD uses poor man's deployment.
Keys are already set up in github.
The CD branches are already created and the deployment works with this config.
> Testing env CD

- .github/workflows/executor_cd_staging.yml
- .github/workflows/facilitator_cd.yml
- .github/workflows/miner_cd_staging.yml
- .github/workflows/validator_cd_staging.yml
- .github/workflows/validator_runner_cd_staging.yml
In order to facilitate deployments to production, we are going to auto-deploy master to staging.
> Automatic staging deployments from master

- .github/workflows/validator_cd_staging.yml
> Triggering CI

- compute_horde/compute_horde/protocol_consts.py
Not sure if this code is being used for anything important right now but just in case.
> fix: horde failure should be marked as an "end state"

- .idea/runConfigurations/Celery___metagraph.xml
- .idea/runConfigurations/Celery___organic_jobs.xml
- .idea/runConfigurations/Celery_beat.xml
- .idea/runConfigurations/Env__Facilitator.xml
- .idea/runConfigurations/Env__Miner.xml
- .idea/runConfigurations/Env__Validator.xml
- .idea/runConfigurations/Facilitator.xml
- .idea/runConfigurations/Facilitator_connector.xml
- .idea/runConfigurations/Miner.xml
- .idea/runConfigurations/precommit.xml
- .idea/runConfigurations/pytest__Executor.xml
- .idea/runConfigurations/pytest__Facilitator.xml
- .idea/runConfigurations/pytest__Miner.xml
- .idea/runConfigurations/pytest__SDK.xml
- .idea/runConfigurations/pytest__Validator.xml
- .idea/runConfigurations/pytest__compute_horde.xml
> run configurations for pycharm

- README.md
> [readme] rolling allowance in the readme

- validator/app/src/compute_horde_validator/validator/scoring/engine.py
- validator/app/src/compute_horde_validator/validator/scoring/tests/test_scoring_engine.py
- validator/app/src/compute_horde_validator/validator/tests/test_other/test_set_scores.py
> switch to allowance-based scoring
