backend-developers-ltd/ComputeHorde

miner/app/src/compute_horde_miner/miner/miner_consumer/layer_utils.py
validator/app/src/compute_horde_validator/validator/management/commands/connect_facilitator.py

This PR fixes 2 instances of mismatch that are occurring:
1. `docker_process_exit_status` field being `None` on timeout, failing validation for `ExecutorFailed` on miner's executor->validator layer
2. Structure of `JobStatusUpdate.miner_response` being different on `status=rejected` failing validation on facilitator

Fix schema differences

---

executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
miner/envs/runner-staging/data/docker-compose.yml
miner/envs/runner/data/docker-compose.yml

- Remove the logic of docker image clean-up after job execution.
- `docuum` keeps track of docker events. When docker image storage crosses a threshold it evicts the least recently used images.
- Image storage threshold can be configured with the `DOCKER_STORAGE_THRESHOLD` environment variable.
- A default threshold of `50 GB` is arbitrarily chosen.

Docker image LRU eviction in miner (executor)

---

compute_horde/compute_horde/miner_client/base.py
validator/app/src/compute_horde_validator/validator/management/commands/connect_facilitator.py

The validators/miners trying to connect a miner that is refusing the connection can lead to an infinite loop, because miner connection was retried forever (with exponential backoff). As a consequence, the status of the job is never reported in the facilitator.
This PR adds a max-retry limit of 5 for connecting to a miner. If the limit is exceeded, the job is considered failed and reported as such to the facilitator.
Previously on facilitator:
After this PR:
**Note:** the `MinerConnectionError` exception is purposefully not handled in the executor, so that miners can notice fast if their executors cannot connect to their miners. This is often an issue with miner's configuration.

Handle miner connection refusal in validator

---

README.md
install_miner.sh
install_validator.sh

heredocs inside heredocs! (╯°□°）╯︵ ┻━┻
The scripts have a lot of repeated code. But I decided to keep them like that, as de-duplicating them would mean complicated templating/code-generation.
But we *may* want to do it anyway, if we *need* similar installer scripts for staging and preprod.
There's one `shellcheck` warning in the scripts:
```
❯ shellcheck install_validator.sh
In install_validator.sh line 25:
ssh "$SSH_DESTINATION" <<ENDSSH
^----^ SC2087 (warning): Quote 'ENDSSH' to make here document expansions happen on the server side rather than on the client.
For more information:
https://www.shellcheck.net/wiki/SC2087 -- Quote 'ENDSSH' to make here docum...
```
but that is intended. It could be circumvented by preparing the `tmpvars` file locally (in `/tmp` or something) and then …

Add installer scripts for miner & validator

---

compute_horde/compute_horde/miner_client/base.py
validator/app/src/compute_horde_validator/validator/facilitator_client.py

This should prevent observed hanging on receiving data in facilitator connector.
Issue summarized in:
https://github.com/python-websockets/websockets/issues/867
Longer discussion:
https://github.com/python-websockets/websockets/issues/865
Solution also added in MinerClient.send_model

Manually release control after websocket.send

---

compute_horde/compute_horde/transport/__init__.py
compute_horde/compute_horde/transport/stub.py
executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py
validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
validator/app/src/compute_horde_validator/validator/tests/mock_generator.py
validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs.py
validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/conftest.py
validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/mock_generator.py
validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_dance_incentives.py
validator/app/src/compute_horde_validator/validator/tests/test_synthetic_jobs/test_single_miner.py
validator/app/src/compute_horde_validator/validator/tests/transport.py

This PR introduces a drop-in integration alternative for all tests that are currently in `test_utils.py`, except `test_create_and_run_synthetic_job_batch`. Integration tests replacing the latter will probably go in a separate PR (there is an idea to test multiple miners at once there) to keep this one manageable.

Make synthetic jobs tests more integration

---

validator/app/src/compute_horde_validator/validator/tasks.py

When not using `raise` statement, the code
```python
@contextlib.contextmanager
def save_event_on_error(subtype):
try:
yield
except Exception:
save_weight_setting_failure(subtype, traceback.format_exc(), {})
```
will suppress the error and return `None`, which will lead to weird errors like https://sentry.reef.pl/organizations/reef-technologies/issues/730505/?project=61&referrer=slack, where `get_subtensor()` returns `None`.

Raise original exception when using save_event_on_error

---

compute_horde/compute_horde/miner_client/base.py
compute_horde/compute_horde/miner_client/organic.py
compute_horde/compute_horde/transport/stub.py
compute_horde/compute_horde/utils.py
compute_horde/noxfile.py
compute_horde/tests/test_organic_miner_client.py
compute_horde/tests/test_run_organic_job.py
compute_horde/tests/test_utils.py
validator/app/src/compute_horde_validator/validator/organic_jobs/miner_client.py
validator/app/src/compute_horde_validator/validator/organic_jobs/miner_driver.py
validator/app/src/compute_horde_validator/validator/tests/test_utils.py
validator/app/src/compute_horde_validator/validator/utils.py

- Move miner client for running organic jobs from validator to the library, removing django specific things.
- Add django specific things (system event models etc.) in the subclass in validator.

Add django-less miner client in library

---

miner/app/src/compute_horde_miner/miner/executor_manager/_internal/base.py

It was returning the same pool regardless of the passed in `executor_class`. The `executor_class` was being overridden inside in the for loop for using the same variable name.

Fix BaseExecutorManager.get_executor_class_pool

---

compute_horde/compute_horde/em_protocol/miner_requests.py
compute_horde/compute_horde/mv_protocol/validator_requests.py
executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
miner/app/src/compute_horde_miner/miner/miner_consumer/executor_interface.py
miner/app/src/compute_horde_miner/miner/miner_consumer/validator_interface.py
miner/app/src/compute_horde_miner/miner/tests/executor_manager.py
validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/base.py
validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/gpu_hashcat.py
validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/llm_prompts.py

- Add optional `volume` field to initial job request without bumping protocol version
- Volume cannot be sent in initial job request and job request at the same time
- Move the volume in synthetic hashcat jobs to the initial job request

Initial job request volume

---

executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py

Images mentioned as `docker.io/backenddevelopersltd/...` are failing due to the prefix check.

Fix docker image prefix check

---

validator/app/src/compute_horde_validator/validator/locks.py

The `get_advisory_lock` function documentation says that the function must be called within an atomic block and the lock will be released automatically after the atomic block ends. But that is not the case.
The advisory lock used here (`pg_try_advisory_lock`) is a session-level lock. It does not require an atomic block. To unlock, either `pg_advisory_unlock` needs to be explicitly called or the session needs to end.
This PR uses `pg_try_advisory_xact_lock` to create transaction level lock. It works as the function documentation.

Use transaction specific advisory lock

---

compute_horde/compute_horde/miner_client/organic.py
compute_horde/tests/test_organic_miner_client.py
compute_horde/tests/test_run_organic_job.py
validator/app/src/compute_horde_validator/validator/organic_jobs/miner_driver.py
validator/app/src/compute_horde_validator/validator/tests/helpers.py
validator/app/src/compute_horde_validator/validator/tests/test_miner_driver.py

The organic client does not properly handle the job accept/reject message before checking for executor ready/failed message.

Properly handle miner responses in organic client

---

validator/envs/runner/data/docker-compose.yml

The label was removed by mistake in a receipt change.

Mark validator celery containers for auto update

---

README.md
validator/README.md

A6000 README instructions

---

README.md
validator/README.md

Readme changes after a validator installation call

---

compute_horde/README.md
compute_horde/compute_horde/blockchain/apps.py
compute_horde/compute_horde/blockchain/block_cache.py
compute_horde/compute_horde/blockchain/tasks.py
compute_horde/compute_horde/settings.py
compute_horde/noxfile.py
compute_horde/pdm.lock
compute_horde/pyproject.toml
compute_horde/tests/settings.py
compute_horde/tests/test_blockchain.py
compute_horde/uv.lock
executor/uv.lock
miner/uv.lock
uv.lock
validator/uv.lock

Issue: https://reeftechnologies.atlassian.net/browse/COM-353.
I created a new Django app for it, `compute_horde.blockchain`, so that other apps can easily use the background task to update the cache by just adding it to their installed apps. Can be moved somewhere else if needed.
Tested with unit tests and manually by adding this app and background task to the validator's settings.
Measured speed – block number from cache takes ~0.002 s, from subtensor ~0.1 s.
Usage:
* Add `compute_horde.blockchain` to INSTALLED_APPS in the settings module.
* Add `compute_horde.blockchain.tasks.update_block_cache` as a celery beat task with some reasonable frequency (like 1 or 2 s)
* To get the current block number from cache, use `aget_current_block` (or `get_current_block`).

Add block number cache

---

miner/app/envs/prod/Dockerfile

After migrating to uv, packages get installed in .venv in the sources directory, not globally.
This tells pip to install things in the same .venv as other app dependencies, fixing miner vendor scripts.

point pip in vendor scripts to install stuff in the venv

---

miner/app/src/compute_horde_miner/miner/dynamic_config.py
miner/app/src/compute_horde_miner/miner/tests/settings.py
miner/app/src/compute_horde_miner/settings.py
validator/app/src/compute_horde_validator/settings.py
validator/app/src/compute_horde_validator/validator/dynamic_config.py
validator/app/src/compute_horde_validator/validator/tests/settings.py

(!) Look into this after receipts transfer is merged.
- removes configholder whose purpose was to cache constance config
- enables constance's built-in cache instead

Constance cache

---

compute_horde/compute_horde/executor_class.py
executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
miner/app/src/compute_horde_miner/miner/executor_manager/_internal/base.py
miner/app/src/compute_horde_miner/miner/executor_manager/_internal/dev.py
miner/app/src/compute_horde_miner/miner/executor_manager/_internal/docker.py

Changes summary:
- Increase executor timeouts (that's required as 6 min is too low for SN21 jobs, it needs at least 12–15 min on A6000). I'm open to adjusting the values or doing it some better way.
- Add Adal's Huggingface download optimization env var to dev executor class
- Add more logging to executor (that includes job's stdout and stderr, if that's too much I can remove it)
- Add more logging to executor manager, including when executors are killed, it wasn't clear to me what's happening and why

Prepare executor for SN21 integration

---

compute_horde/compute_horde/base/volume.py
executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py

For SN21 integration we want to be able download some files from a huge dataset repo without having to download the entire repository. I added two things to make it possible:
*  `repo_type`: must be `"dataset"` for dataset repositories, otherwise it doesn't work. Can be left as `None` for our current usage (models).
* `allow_patterns`: this is passed as-is to the hugginface_hub function. I use it to specify the list of files that I need, but I left the original signature (`str | list[str]`) because we might want to specify a single pattern at some point, I saw something like that in the SDK design issue.

Allow specifying files to download in HuggingfaceVolume

---

validator/app/src/compute_horde_validator/settings.py

I did something like this in `.env`:
```env
FACILITATOR_URI=ws://localhost:8000/ws/v0/ # wss://staging.facilitator.computehorde.io/ws/v0/
```
This resulted in a space on the end of the URI, which in turn caused some hard-to debug errors (400 Bad Request, no explanation in response or logs) when trying to connect to the facilitator. I wasted some time on that so maybe this `.strip()` is not a bad idea.

Add strip() to settings.FACILITATOR_URI

---

compute_horde/tests/conftest.py
compute_horde/tests/test_certificate.py
compute_horde/tests/test_transport.py

- skip certificate nginx container tests on non-linux platforms
- properly cleanup containers on failed tests
- make transport tests pick random ports, so they are parallelizable (in case we decide to use `pytest-xdist` in the future)

Improve some tests of compute_horde

---

validator/app/src/compute_horde_validator/validator/organic_jobs/facilitator_client.py

This is for local dev only; allows using a preconfigured "debug" miner data to run an organic job - if the miner gets explicitly selected for the job.

use debug miner for organic jobs if selected and configured

---

validator/app/src/compute_horde_validator/validator/tasks.py

When celery tries to kill a worker (due to timeouts etc.), it raises `SystemExit`. So `current_block` variable is not set in the `except` block.

Fix UnboundLocalError

---

facilitator/app/src/project/settings.py
facilitator/uv.lock

Same as #411, I didn't do it in facilitator then because I never saw this error but now I did.
> When trying to write something in Django shell, DEBUG-level logs from some ipython parser appear during autocomplete (tab) and wreck the console like:
> 
> ```python
> In [1]: Validator.obDEBUG 2025-02-12 14:25:51,173 parso.python.diff diff parser start
> DEBUG 2025-02-12 14:25:51,173 parso.python.diff line_lengths old: 1; new: 1
> DEBUG 2025-02-12 14:25:51,173 parso.python.diff -> code[replace] old[1:1] new[1:1]
> DEBUG 2025-02-12 14:25:51,173 parso.python.diff parse_part from 1 to 1 (to 0 in part parser)
> DEBUG 2025-02-12 14:25:51,173 parso.python.diff diff parser end
> ```
> To reproduce, run uv run app/src/manage.py shell_plus (or shell) in any of our apps and try to autocomplete …

Fix DEBUG-level logs spamming in facilitator django shell

---

compute_horde/compute_horde/base/volume.py
compute_horde_sdk/src/_compute_horde_models/volume.py

It looked like this, but much much longer:
```
type='job.new' message_type='V2JobRequest' signature=None uuid='asdkojas' executor_class=<ExecutorClass.always_on__gpu_24gb: 'always_on.gpu-24gb'> docker_image='derp' raw_script='bash' args=[] env={} use_gpu=True volume=InlineVolume(volume_type=<VolumeType.inline: 'inline'>, contents='mc/oeqGkOXnPJJspwN/BN6EoO4A2PLYjgqyq8YZE663IZE/bMnJazKDzWwH1LCjol5+PAsmFtDh1aGM/YDRNCwcccBXBdoeI3+DQuLUdjNMDQNZ6DO7slPazafKXZFe0jCQukvlIqP5EDaxBSuHMNc9eVCem4i2MBQhlmXxKsmh1HX2fNQNeU7P2ttPAI+50NEDL0sgNBYEZImmyDjtWR5CYvNKt/S3oX/BqpSD9rULXOdI6vy2qjKVBr3cMomCo0Nl+bmZDQc+4YKCKu+Q2sDOzDaZu16yRGW2UaXTYErVFxrXXP8S3TQBRgc0UaAUzxEJXI1snh+JMvGSvHiDuvdx0lflL8prKevxM+cYd6tOx956J+cx+08thwrNoOV3B/ansgr4oE3/bXvOzTFz4fIvWYkycSvAyJXV1jOZs65zh38/2QmVasfuOcXh0VFoqy0F0WMA/iVBqjVUh+v5 …
```

Fix InlineVolume printing long contents in logs

---

compute_horde_sdk/src/compute_horde_sdk/_internal/sdk.py

SDK: remove `run_cross_validation` param

---

validator/app/src/compute_horde_validator/validator/organic_jobs/facilitator_client.py

`code` and `reason` are deprecated and provide misleading info. The exception class now has a `__str__` method that seems to work much better here.
Before:
```
validator connection closed with code <CloseCode.ABNORMAL_CLOSURE: 1006> and reason '', reconnecting...
```
Now:
```
validator connection closed: sent 1009 (message too big) frame with 1070709 bytes exceeds limit of 1048576 bytes; no close frame received, reconnecting...
```

Improve validator logging on websocket error

---

compute_horde/compute_horde/miner_client/organic.py
validator/app/src/compute_horde_validator/settings.py

The executor errors out if the volumes are being sent twice. Changed that so that now for organic jobs they are only sent in the Initial job request.
As for the settings change, Constance crashes the entire admin panel because 10 is not a float…

Fix organic job volumes being sent twice

---

compute_horde_sdk/src/compute_horde_sdk/_internal/models.py

We had problems where the inline volumes exceeded 1 MB, compression brings that down (for that particular use case) to 0.27 MB, which is useful for SN15 validation.
Unpacking them works as-is, no changes needed.

SDK: add zip compression to inline volumes

---

validator/app/src/compute_horde_validator/validator/tests/conftest.py
validator/app/src/pytest.ini

I suspected that there are some dangling asyncio tasks that are using redis/postgres connections. I fixed some, but the error still persists. Maybe my suspicions are unfounded and django keeps those connection open anyway? But it is curious that this issue only happens in validator, not in miner or facilitator.
As discussed, I've added ignore flags for these ports.

COM-522 Ignore ResourceWarning for unclosed redis connections

---

validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py

I was initially trying to reproduce / fix an issue where a miner who missed a peak would not be sent any jobs. Couldn't reproduce it, but there are some other minor things I found.

Fix min executor count

---

executor/app/src/compute_horde_executor/executor/management/commands/run_executor.py
executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py

Our current SN15 jobs on ComputeHorde prod executors fail with errors like:
```
Failed to download model from Hugging Face: An error occurred while downloading using hf_transfer. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.
```
On the other hand, this library is useful when it works, because it can reduce the time to download a model by a lot.
Added retires to HF volume downloads with disabling `hf_transfer` after the first try.
It modifies an internal library constant, which is probably not a great solution, but I don't know how to do it better. Using or not `hf_transfer` is decided by an environment variable on import time and can't be parametrized otherwise.
<details><summary>Test script</summary>
```python
import os
from pathlib import Path …
```

Add retries to huggingface volume downloads, also with hf_transfer disabled

---

compute_horde_sdk/src/compute_horde_sdk/_internal/sdk.py
local_stack/send_hello_world_job.py

Let's make `streaming_start_time_limit_sec` optional parameter and default to 5 seconds. It should not be required since it's only used when running streaming jobs.

Make streaming_start_time_limit_sec optional

---

README.md
compute_horde_sdk/README.md
compute_horde_sdk/docs/source/fallback.rst
compute_horde_sdk/docs/source/quickstart.rst
compute_horde_sdk/src/compute_horde_sdk/_internal/fallback/client.py
compute_horde_sdk/src/compute_horde_sdk/_internal/models.py

[sdk docs] Presigned output volume urls

---

validator/app/src/compute_horde_validator/settings.py
validator/app/src/compute_horde_validator/validator/organic_jobs/routing.py
validator/app/src/compute_horde_validator/validator/tests/test_job_routing.py

Allowance will still be deducted and potentially end up negative.

Feature flag for disabling allowance checks in organic job routing

---

executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py
executor/app/src/compute_horde_executor/executor/tests/settings.py

Tests were failing, because:
- `test_artifacts` is producing huge output that GitHub action is not able to handle, causing timeouts.
- GPU mode is not available in CI.

Fix executor tests

---

validator/app/src/compute_horde_validator/validator/tasks.py
validator/app/src/compute_horde_validator/validator/tests/test_manifest_polling.py

If miner does not respond with the manifest, we want to copy only the latest manifest, not all of them. This PR fixes the issue with the fallback query, and adds a test to make sure we will not regress in the future.

Fix manifest polling

---

validator/app/src/compute_horde_validator/validator/migrations/0070_delete_minermanifest_batch_none.py

Cleanup database from the redundant manifests created as a result of a bug fixed in[ this PR](https://github.com/backend-developers-ltd/ComputeHorde/pull/586).

Cleanup manifests

---

validator/app/src/compute_horde_validator/validator/scoring/main_hotkey_querying.py

The main hotkey query incorrectly assumed that the first message received from a miner would be a response to the `V0MainHotkeyMessage`. but other messages may be sent first - the first message a miner sends after successful validator authentication is the `V0ExecutorManifestRequest`. Let's simply wait until we receive the expected response.

Fix main hotkey querying

---

compute_horde/compute_horde/job_errors.py
compute_horde/compute_horde/miner_client/organic.py
compute_horde/compute_horde/protocol_messages.py
executor/app/src/compute_horde_executor/executor/job_driver.py
executor/app/src/compute_horde_executor/executor/job_runner.py
executor/app/src/compute_horde_executor/executor/miner_client.py
executor/app/src/compute_horde_executor/executor/tests/integration/test_main_loop.py
facilitator/app/src/project/core/migrations/0052_alter_jobstatus_status.py
precommit.sh
validator/app/src/compute_horde_validator/validator/management/commands/debug_run_mock_streaming_job_to_miner.py
validator/app/src/compute_horde_validator/validator/organic_jobs/facilitator_client.py
validator/app/src/compute_horde_validator/validator/organic_jobs/miner_driver.py

- Pulled out the 3 main error classes to compute_horde. This way we can throw these during job execution (almost?) anywhere and they should be handled correctly.
- (still, throwing an error where it is not appropriate, e.g. a rejection in an executor JobDriver, will be treated as a generic horde failure)
- Added a helper for wrapping unhandled exceptions into a HordeError, so that they are a bit more consistent
- Explicitly logging exceptions to sentry where they would've been only wrapped and propagated. They are potentially interesting to log.

Pull up common error types to compute_horde

---

validator/app/src/compute_horde_validator/validator/collateral/tasks.py
validator/app/src/compute_horde_validator/validator/collateral/tests/conftest.py
validator/app/src/compute_horde_validator/validator/collateral/tests/helpers/contexts.py
validator/app/src/compute_horde_validator/validator/collateral/tests/helpers/env.py
validator/app/src/compute_horde_validator/validator/collateral/tests/helpers/setup_helpers.py
validator/app/src/compute_horde_validator/validator/collateral/tests/helpers/stubs.py
validator/app/src/compute_horde_validator/validator/collateral/tests/test_collateral.py

Refactor collateral tests to use use clean, reusable testing setup with clear responsibilities and minimal boilerplate.
- `CollateralTestEnvironment` - sets up stubs for Web3, HTTP, Bittensor and config.
- `CollateralTaskHarness` - wires up the test environment for `sync_collaterals` task tests.
- `setup_collateral` and `async_setup_collateral` - DB helpers to set `uid`, `evm_address` and `collateral_wei` on Miner.
- `sync_collaterals` accepts an optional `CollateralTaskDependencies` object, enabling injection of dependencies.

Improve collateral tests

---

.github/workflows/commit_linting.yaml
.gitlint
gitlint_rules/impacts-projects.py

From now on commit messages will be checked against the rules
defined in the .gitlint file in the repo root.
Impacts: validator,miner,sdk,facilitator,executor,lib

ci: add GH action for commit linting
